TimerEdit: Solve GSOD when try to solve timer conflict issues
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/mytest.py", line 210, in processDelay
    callback(*retval)
  File "/usr/lib/enigma2/python/Screens/TimerEdit.py", line 313, in finishedEdit
AttributeError: 'RecordTimerEntry' object has no attribute 'external_prev'

It seems in TimerEntry a attribute external_prev is created so timers
can be removed from external (fallback) tuner to local tuner and back.
When we try to solve timerconflicts which are always local the
external_prev attribute might not exist. By adding the attribute to
RecordTimer the issue should be solved.